# Generated by Django 4.2 on 2023-04-08 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('AwardName', models.TextField()),
                ('date_started', models.DateField()),
                ('Department', models.TextField()),
                ('Issuing_Organization', models.TextField()),
                ('Remark', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='labwebsite\\images\x07wards')),
            ],
        ),
        migrations.CreateModel(
            name='LabMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AcademicProgram', models.CharField(choices=[('PHD', 'PHD'), ('UG', 'UG'), ('PG', 'PG'), ('Alumni', 'Alumni')], max_length=50)),
                ('Department', models.TextField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='labwebsite\\images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('Remark', models.TextField()),
                ('pub_date', models.DateField()),
                ('link', models.URLField()),
                ('members', models.ManyToManyField(to='api.labmember')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('members', models.ManyToManyField(to='api.labmember')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.TextField()),
                ('bio', models.TextField()),
                ('research_interests', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='labwebsite\\images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
