# Generated by Django 4.2 on 2023-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_award_image_alter_labmember_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmember',
            name='AcademicProgram',
            field=models.CharField(choices=[('PHD', 'PHD'), ('UG', 'UG'), ('PG', 'PG'), ('Alumni', 'Alumni'), ('Professor', 'Professor')], max_length=50),
        ),
    ]
