# Generated by Django 4.2 on 2023-04-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_professor_position'),
        ('api', '0005_labmember_achievements_labmember_contact_and_more'),
    ]

    operations = [
    ]
