# Generated by Django 4.2 on 2023-04-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_award_image'),
        ('api', '0006_merge_20230418_1928'),
    ]

    operations = [
    ]
