# Generated by Django 4.2 on 2023-04-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_0006_alter_award_image_0006_merge_20230418_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./images'),
        ),
    ]
