# Generated by Django 4.2 on 2023-04-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_project_image_publication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='labmember',
            name='email',
            field=models.TextField(default=9406878600),
            preserve_default=False,
        ),
    ]
