# Generated by Django 4.2 on 2023-04-22 09:09
# Generated by Django 4.1.3 on 2023-04-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_labmember_email'),
        ('api', '0013_news'),
    ]

    operations = [
    ]
